name: flutter_system_icons
description: A Flutter plugin for retrieving system icons on macOS and other platforms.
version: 0.0.2
homepage: https://github.com/klarity-app/flutter_system_icons

environment:
  sdk: '>=3.4.1 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  riverpod: ^2.3.6
  flutter_riverpod: ^2.3.6
  riverpod_annotation: ^2.1.1
  flutter_hooks: ">=0.18.6 <0.21.0"
  hooks_riverpod: ^2.3.6
  ffi: ^2.0.2
  flutter_rust_bridge: 2.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ">=2.0.0 <6.0.0"
  build_runner: ^2.4.5
  riverpod_generator: ^2.2.3
  integration_test:
    sdk: flutter
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' specifies the class (in Java, Kotlin, Swift, Objective-C, etc.)
  # which should be registered in the plugin registry. This is required for
  # using method channels.
  # The Android 'package' specifies package in which the registered class is.
  # This is required for using method channels on Android.
  # The 'ffiPlugin' specifies that native code should be built and bundled.
  # This is required for using `dart:ffi`.
  # All these are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  #
  # Please refer to README.md for a detailed explanation.
  plugin:
    platforms:
      macos:
        ffiPlugin: true

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
